import { palette } from "./palette"

export const lightColors = {
  palette,
  transparent: "rgba(0, 0, 0, 0)",
  background: palette.lighterGrey,
  backgroundSecondary: palette.white,
  surface: palette.white,
  surfaceElevated: palette.offWhite,
  primary: palette.blue,
  primaryDarker: palette.blue,
  line: palette.lighterGrey,
  border: palette.lightGrey,
  text: palette.darkGrey,
  textSecondary: palette.midGrey,
  textInverse: palette.white,
  dim: palette.lightGrey,
  secondary: palette.orange,
  error: palette.red,
  success: palette.green,
  warning: palette.orange,
  info: palette.lightBlue,
  modalBackground: "rgba(0, 0, 0, 0.5)",
  inputBackground: palette.white,
  inputBorder: palette.lightGrey,
  cardBackground: palette.white,
  tabBarBackground: palette.white,
  tabBarActive: palette.blue,
  tabBarInactive: palette.midGrey,
  headerBackground: palette.white,
  headerText: palette.darkGrey,
  buttonPrimary: palette.blue,
  buttonPrimaryText: palette.white,
  buttonSecondary: palette.lighterGrey,
  buttonSecondaryText: palette.darkGrey,
  ripple: "rgba(49, 91, 90, 0.12)",
  shadow: "rgba(0, 0, 0, 0.1)",
  divider: palette.lighterGrey,
  iconDefault: palette.midGrey,
  iconActive: palette.blue,
  link: palette.lightBlue,
  placeholder: palette.midGrey,
  backdrop: "rgba(0, 0, 0, 0.4)",
  statusBar: palette.blue,
  transactionPositive: palette.green,
  transactionNegative: palette.red,
  transactionPending: palette.orange,
  qrCodeBackground: palette.white,
  qrCodeForeground: palette.black,
  mapBackground: palette.lighterGrey,
  pinDot: palette.darkGrey,
  pinDotFilled: palette.blue,
}

export const darkColors = {
  palette,
  transparent: "rgba(0, 0, 0, 0)",
  background: "#0d0d0d",
  backgroundSecondary: "#1a1a1a",
  surface: "#1a1a1a",
  surfaceElevated: "#262626",
  primary: "#5a9a99",
  primaryDarker: "#4a7a79",
  line: "#2a2a2a",
  border: "#333333",
  text: "#ffffff",
  textSecondary: "#e0e0e0",
  textInverse: palette.darkGrey,
  dim: "#999999",
  secondary: palette.orange,
  error: "#ff5252",
  success: "#5cb85c",
  warning: palette.orange,
  info: "#5c9cff",
  modalBackground: "rgba(0, 0, 0, 0.85)",
  inputBackground: "#1a1a1a",
  inputBorder: "#404040",
  cardBackground: "#1a1a1a",
  tabBarBackground: "#1a1a1a",
  tabBarActive: "#5a9a99",
  tabBarInactive: "#999999",
  headerBackground: "#1a1a1a",
  headerText: "#ffffff",
  buttonPrimary: "#5a9a99",
  buttonPrimaryText: "#ffffff",
  buttonSecondary: "#262626",
  buttonSecondaryText: "#ffffff",
  ripple: "rgba(90, 154, 153, 0.12)",
  shadow: "rgba(0, 0, 0, 0.3)",
  divider: "#2a2a2a",
  iconDefault: "#cccccc",
  iconActive: "#5a9a99",
  link: "#7aa3ff",
  placeholder: "#808080",
  backdrop: "rgba(0, 0, 0, 0.7)",
  statusBar: "#0d0d0d",
  transactionPositive: "#5cb85c",
  transactionNegative: "#ff5252",
  transactionPending: palette.orange,
  qrCodeBackground: palette.white,
  qrCodeForeground: palette.black,
  mapBackground: "#0d0d0d",
  pinDot: "#cccccc",
  pinDotFilled: "#5a9a99",
}

export type ThemeColors = typeof lightColors